# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        terraform { 
      required_version = ">=1.0.0"
      required_providers {
        aws = {
          source = "hashicorp/aws"
          version = "5.16"
        }
      }
    }

    provider "aws" {
      region  = "eu-west-1"
      profile = "alex-meli-card-admincli"
    }

