# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
   terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.17"
    }
  }
}

provider "aws" {
  region                   = "eu-west-1"
  shared_credentials_files =["C:/Users/alex/.aws/credentials"]
  profile                  = "alex-meli-card-admincli"
}

